import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import NavigationProvider from "@/Context";

const inter = Inter({ subsets: ["latin"] });
const lexend = Lexend({ weight: "300", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "cyparta-login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} flex`}>
        <NavigationProvider>
          <SideBar/>
          {children}
        </NavigationProvider>
        </body>
    </html>
  );
}
